// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegisterAPII.DATA;

#nullable disable

namespace RegisterAPII.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250722092656_ssssssssss")]
    partial class ssssssssss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegisterAPII.Models.Accounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "batolmagdy092@gmail.com",
                            FullName = "User 1 (Role 1)",
                            IsActive = true,
                            LoginId = 1,
                            NationalID = "30101010000001",
                            PasswordHash = "",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2.role1@example.com",
                            FullName = "User 2 (Role 1)",
                            IsActive = true,
                            LoginId = 2,
                            NationalID = "30101010000002",
                            PasswordHash = "",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user3.role1@example.com",
                            FullName = "User 3 (Role 1)",
                            IsActive = true,
                            LoginId = 3,
                            NationalID = "30101010000003",
                            PasswordHash = "",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user4.role1@example.com",
                            FullName = "User 4 (Role 1)",
                            IsActive = true,
                            LoginId = 4,
                            NationalID = "30101010000004",
                            PasswordHash = "",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user5.role1@example.com",
                            FullName = "User 5 (Role 1)",
                            IsActive = true,
                            LoginId = 5,
                            NationalID = "30101010000005",
                            PasswordHash = "",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user6.role2@example.com",
                            FullName = "User 6 (Role 2)",
                            IsActive = true,
                            LoginId = 6,
                            NationalID = "30101010000006",
                            PasswordHash = "",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user7.role2@example.com",
                            FullName = "User 7 (Role 2)",
                            IsActive = true,
                            LoginId = 7,
                            NationalID = "30101010000007",
                            PasswordHash = "",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user8.role2@example.com",
                            FullName = "User 8 (Role 2)",
                            IsActive = true,
                            LoginId = 8,
                            NationalID = "30101010000008",
                            PasswordHash = "",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user9.role2@example.com",
                            FullName = "User 9 (Role 2)",
                            IsActive = true,
                            LoginId = 9,
                            NationalID = "30101010000009",
                            PasswordHash = "",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user10.role2@example.com",
                            FullName = "User 10 (Role 2)",
                            IsActive = true,
                            LoginId = 10,
                            NationalID = "30101010000010",
                            PasswordHash = "",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user11.role3@example.com",
                            FullName = "User 11 (Role 3)",
                            IsActive = true,
                            LoginId = 11,
                            NationalID = "30101010000011",
                            PasswordHash = "",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user12.role3@example.com",
                            FullName = "User 12 (Role 3)",
                            IsActive = true,
                            LoginId = 12,
                            NationalID = "30101010000012",
                            PasswordHash = "",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user13.role3@example.com",
                            FullName = "User 13 (Role 3)",
                            IsActive = true,
                            LoginId = 13,
                            NationalID = "30101010000013",
                            PasswordHash = "",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user14.role3@example.com",
                            FullName = "User 14 (Role 3)",
                            IsActive = true,
                            LoginId = 14,
                            NationalID = "30101010000014",
                            PasswordHash = "",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user15.role3@example.com",
                            FullName = "User 15 (Role 3)",
                            IsActive = true,
                            LoginId = 15,
                            NationalID = "30101010000015",
                            PasswordHash = "",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user16.role4@example.com",
                            FullName = "User 16 (Role 4)",
                            IsActive = true,
                            LoginId = 16,
                            NationalID = "30101010000016",
                            PasswordHash = "",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user17.role4@example.com",
                            FullName = "User 17 (Role 4)",
                            IsActive = true,
                            LoginId = 17,
                            NationalID = "30101010000017",
                            PasswordHash = "",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user18.role4@example.com",
                            FullName = "User 18 (Role 4)",
                            IsActive = true,
                            LoginId = 18,
                            NationalID = "30101010000018",
                            PasswordHash = "",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user19.role4@example.com",
                            FullName = "User 19 (Role 4)",
                            IsActive = true,
                            LoginId = 19,
                            NationalID = "30101010000019",
                            PasswordHash = "",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user20.role4@example.com",
                            FullName = "User 20 (Role 4)",
                            IsActive = true,
                            LoginId = 20,
                            NationalID = "30101010000020",
                            PasswordHash = "",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user21.role5@example.com",
                            FullName = "User 21 (Role 5)",
                            IsActive = true,
                            LoginId = 21,
                            NationalID = "30101010000021",
                            PasswordHash = "",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user22.role5@example.com",
                            FullName = "User 22 (Role 5)",
                            IsActive = true,
                            LoginId = 22,
                            NationalID = "30101010000022",
                            PasswordHash = "",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user23.role5@example.com",
                            FullName = "User 23 (Role 5)",
                            IsActive = true,
                            LoginId = 23,
                            NationalID = "30101010000023",
                            PasswordHash = "",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user24.role5@example.com",
                            FullName = "User 24 (Role 5)",
                            IsActive = true,
                            LoginId = 24,
                            NationalID = "30101010000024",
                            PasswordHash = "",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user25.role5@example.com",
                            FullName = "User 25 (Role 5)",
                            IsActive = true,
                            LoginId = 25,
                            NationalID = "30101010000025",
                            PasswordHash = "",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user26.role6@example.com",
                            FullName = "User 26 (Role 6)",
                            IsActive = true,
                            LoginId = 26,
                            NationalID = "30101010000026",
                            PasswordHash = "",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user27.role6@example.com",
                            FullName = "User 27 (Role 6)",
                            IsActive = true,
                            LoginId = 27,
                            NationalID = "30101010000027",
                            PasswordHash = "",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user28.role6@example.com",
                            FullName = "User 28 (Role 6)",
                            IsActive = true,
                            LoginId = 28,
                            NationalID = "30101010000028",
                            PasswordHash = "",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user29.role6@example.com",
                            FullName = "User 29 (Role 6)",
                            IsActive = true,
                            LoginId = 29,
                            NationalID = "30101010000029",
                            PasswordHash = "",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user30.role6@example.com",
                            FullName = "User 30 (Role 6)",
                            IsActive = true,
                            LoginId = 30,
                            NationalID = "30101010000030",
                            PasswordHash = "",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user31.role7@example.com",
                            FullName = "User 31 (Role 7)",
                            IsActive = true,
                            LoginId = 31,
                            NationalID = "30101010000031",
                            PasswordHash = "",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user32.role7@example.com",
                            FullName = "User 32 (Role 7)",
                            IsActive = true,
                            LoginId = 32,
                            NationalID = "30101010000032",
                            PasswordHash = "",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user33.role7@example.com",
                            FullName = "User 33 (Role 7)",
                            IsActive = true,
                            LoginId = 33,
                            NationalID = "30101010000033",
                            PasswordHash = "",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user34.role7@example.com",
                            FullName = "User 34 (Role 7)",
                            IsActive = true,
                            LoginId = 34,
                            NationalID = "30101010000034",
                            PasswordHash = "",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user35.role7@example.com",
                            FullName = "User 35 (Role 7)",
                            IsActive = true,
                            LoginId = 35,
                            NationalID = "30101010000035",
                            PasswordHash = "",
                            RoleId = 7
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("ClassRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeId = 1,
                            Name = "Wheeler 1"
                        },
                        new
                        {
                            Id = 2,
                            GradeId = 1,
                            Name = "Wheeler 2"
                        },
                        new
                        {
                            Id = 3,
                            GradeId = 1,
                            Name = "Wheeler 3"
                        },
                        new
                        {
                            Id = 4,
                            GradeId = 1,
                            Name = "Wheeler 4"
                        },
                        new
                        {
                            Id = 5,
                            GradeId = 2,
                            Name = "Senior 1"
                        },
                        new
                        {
                            Id = 6,
                            GradeId = 2,
                            Name = "Senior 2"
                        },
                        new
                        {
                            Id = 7,
                            GradeId = 2,
                            Name = "Senior 3"
                        },
                        new
                        {
                            Id = 8,
                            GradeId = 2,
                            Name = "Senior 4"
                        },
                        new
                        {
                            Id = 9,
                            GradeId = 3,
                            Name = "Junior 1"
                        },
                        new
                        {
                            Id = 10,
                            GradeId = 3,
                            Name = "Junior 2"
                        },
                        new
                        {
                            Id = 11,
                            GradeId = 3,
                            Name = "Junior 3"
                        },
                        new
                        {
                            Id = 12,
                            GradeId = 3,
                            Name = "Junior 4"
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wheeler"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Senior"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Junior"
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.LoginAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Email = "batolmagdy092@gmail.com",
                            NationalID = "30101010000001",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Email = "user2.role1@example.com",
                            NationalID = "30101010000002",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            Email = "user3.role1@example.com",
                            NationalID = "30101010000003",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            Email = "user4.role1@example.com",
                            NationalID = "30101010000004",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            Email = "user5.role1@example.com",
                            NationalID = "30101010000005",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 6,
                            Email = "user6.role2@example.com",
                            NationalID = "30101010000006",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 7,
                            Email = "user7.role2@example.com",
                            NationalID = "30101010000007",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 8,
                            Email = "user8.role2@example.com",
                            NationalID = "30101010000008",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 9,
                            Email = "user9.role2@example.com",
                            NationalID = "30101010000009",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 10,
                            Email = "user10.role2@example.com",
                            NationalID = "30101010000010",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 11,
                            Email = "user11.role3@example.com",
                            NationalID = "30101010000011",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 12,
                            Email = "user12.role3@example.com",
                            NationalID = "30101010000012",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 13,
                            Email = "user13.role3@example.com",
                            NationalID = "30101010000013",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 14,
                            Email = "user14.role3@example.com",
                            NationalID = "30101010000014",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 15,
                            Email = "user15.role3@example.com",
                            NationalID = "30101010000015",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 16,
                            Email = "user16.role4@example.com",
                            NationalID = "30101010000016",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 17,
                            Email = "user17.role4@example.com",
                            NationalID = "30101010000017",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 18,
                            Email = "user18.role4@example.com",
                            NationalID = "30101010000018",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 19,
                            Email = "user19.role4@example.com",
                            NationalID = "30101010000019",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 20,
                            Email = "user20.role4@example.com",
                            NationalID = "30101010000020",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 21,
                            Email = "user21.role5@example.com",
                            NationalID = "30101010000021",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 22,
                            Email = "user22.role5@example.com",
                            NationalID = "30101010000022",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 23,
                            Email = "user23.role5@example.com",
                            NationalID = "30101010000023",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 24,
                            Email = "user24.role5@example.com",
                            NationalID = "30101010000024",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 25,
                            Email = "user25.role5@example.com",
                            NationalID = "30101010000025",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 26,
                            AccountId = 26,
                            Email = "user26.role6@example.com",
                            NationalID = "30101010000026",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 27,
                            AccountId = 27,
                            Email = "user27.role6@example.com",
                            NationalID = "30101010000027",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 28,
                            AccountId = 28,
                            Email = "user28.role6@example.com",
                            NationalID = "30101010000028",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 29,
                            AccountId = 29,
                            Email = "user29.role6@example.com",
                            NationalID = "30101010000029",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 30,
                            AccountId = 30,
                            Email = "user30.role6@example.com",
                            NationalID = "30101010000030",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 31,
                            AccountId = 31,
                            Email = "user31.role7@example.com",
                            NationalID = "30101010000031",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 32,
                            AccountId = 32,
                            Email = "user32.role7@example.com",
                            NationalID = "30101010000032",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 33,
                            AccountId = 33,
                            Email = "user33.role7@example.com",
                            NationalID = "30101010000033",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 34,
                            AccountId = 34,
                            Email = "user34.role7@example.com",
                            NationalID = "30101010000034",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 35,
                            AccountId = 35,
                            Email = "user35.role7@example.com",
                            NationalID = "30101010000035",
                            Password = "StrongPassword123"
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Student"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Specialist"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "It"
                        },
                        new
                        {
                            RoleId = 6,
                            Name = "Teacher"
                        },
                        new
                        {
                            RoleId = 7,
                            Name = "Engineer"
                        },
                        new
                        {
                            RoleId = 8,
                            Name = "Parent"
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("sessionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            FromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sessionNo = 1
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            FromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sessionNo = 2
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 3,
                            FromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sessionNo = 3
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 4,
                            FromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sessionNo = 4
                        },
                        new
                        {
                            Id = 5,
                            ClassId = 5,
                            FromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sessionNo = 5
                        },
                        new
                        {
                            Id = 6,
                            ClassId = 6,
                            FromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sessionNo = 6
                        },
                        new
                        {
                            Id = 7,
                            ClassId = 7,
                            FromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sessionNo = 7
                        },
                        new
                        {
                            Id = 8,
                            ClassId = 8,
                            FromDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ToDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            sessionNo = 8
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BadNotesJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysAbsent")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodNotesJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 0,
                            ClassId = 2,
                            CreatedAt = new DateTime(2025, 7, 22, 9, 26, 55, 768, DateTimeKind.Utc).AddTicks(5534),
                            DaysAbsent = 0,
                            Name = "Student 1"
                        },
                        new
                        {
                            Id = 2,
                            Age = 0,
                            ClassId = 2,
                            CreatedAt = new DateTime(2025, 7, 22, 9, 26, 55, 768, DateTimeKind.Utc).AddTicks(5537),
                            DaysAbsent = 0,
                            Name = "Student 2"
                        },
                        new
                        {
                            Id = 3,
                            Age = 0,
                            ClassId = 3,
                            CreatedAt = new DateTime(2025, 7, 22, 9, 26, 55, 768, DateTimeKind.Utc).AddTicks(5538),
                            DaysAbsent = 0,
                            Name = "Student 3"
                        },
                        new
                        {
                            Id = 4,
                            Age = 0,
                            ClassId = 3,
                            CreatedAt = new DateTime(2025, 7, 22, 9, 26, 55, 768, DateTimeKind.Utc).AddTicks(5539),
                            DaysAbsent = 0,
                            Name = "Student 4"
                        },
                        new
                        {
                            Id = 5,
                            Age = 0,
                            ClassId = 4,
                            CreatedAt = new DateTime(2025, 7, 22, 9, 26, 55, 768, DateTimeKind.Utc).AddTicks(5540),
                            DaysAbsent = 0,
                            Name = "Student 5"
                        },
                        new
                        {
                            Id = 6,
                            Age = 0,
                            ClassId = 4,
                            CreatedAt = new DateTime(2025, 7, 22, 9, 26, 55, 768, DateTimeKind.Utc).AddTicks(5541),
                            DaysAbsent = 0,
                            Name = "Student 6"
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.SubordinateTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassRoomId")
                        .HasColumnType("int");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SubordinateAccountId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorAccountId")
                        .HasColumnType("int");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("subordinateTickets");
                });

            modelBuilder.Entity("RegisterAPII.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessEntity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            BusinessEntity = "Behaviour",
                            Name = "Late",
                            OrderNo = 10
                        },
                        new
                        {
                            Id = 7,
                            BusinessEntity = "Behaviour",
                            Name = "Eating",
                            OrderNo = 30
                        },
                        new
                        {
                            Id = 10,
                            BusinessEntity = "Behaviour",
                            Name = "SideTalks",
                            OrderNo = 20
                        },
                        new
                        {
                            Id = 12,
                            BusinessEntity = "Absence",
                            Name = "Absence",
                            OrderNo = 10
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.Accounts", b =>
                {
                    b.HasOne("RegisterAPII.Models.LoginAccount", "LoginAccount")
                        .WithOne("Accounts")
                        .HasForeignKey("RegisterAPII.Models.Accounts", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegisterAPII.Models.Role", "Role")
                        .WithMany("Account")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoginAccount");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RegisterAPII.Models.ClassRoom", b =>
                {
                    b.HasOne("RegisterAPII.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("RegisterAPII.Models.Session", b =>
                {
                    b.HasOne("RegisterAPII.Models.ClassRoom", "Class")
                        .WithMany("Sessions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("RegisterAPII.Models.StudentProfile", b =>
                {
                    b.HasOne("RegisterAPII.Models.ClassRoom", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("RegisterAPII.Models.ClassRoom", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("RegisterAPII.Models.LoginAccount", b =>
                {
                    b.Navigation("Accounts")
                        .IsRequired();
                });

            modelBuilder.Entity("RegisterAPII.Models.Role", b =>
                {
                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
