// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegisterAPII.DATA;

#nullable disable

namespace RegisterAPII.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250721085328_dattttttttttte")]
    partial class dattttttttttte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegisterAPII.Models.Accounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoginId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user1.role1@example.com",
                            FullName = "User 1 (Role 1)",
                            IsActive = true,
                            LoginId = 1,
                            NationalID = "30101010000001",
                            PasswordHash = "",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2.role1@example.com",
                            FullName = "User 2 (Role 1)",
                            IsActive = true,
                            LoginId = 2,
                            NationalID = "30101010000002",
                            PasswordHash = "$2a$11$u3f.mJ4FvGgB3Oa8n.dJ9eA.a9K.L4k5b2mC6n7o8pQ9r0sT1uV2w",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user3.role1@example.com",
                            FullName = "User 3 (Role 1)",
                            IsActive = true,
                            LoginId = 3,
                            NationalID = "30101010000003",
                            PasswordHash = "$2a$11$xY1z.a2B3c4D5e6F7g8H9iJ0kL1mN2oP3qR4sT5uV6wX7yZ8A9b0c",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user4.role1@example.com",
                            FullName = "User 4 (Role 1)",
                            IsActive = true,
                            LoginId = 4,
                            NationalID = "30101010000004",
                            PasswordHash = "$2a$11$C1d2E3f4G5h6I7j8K9l0M1n2O3p4Q5r6S7t8U9v0W1x2Y3z4A5b6c",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user5.role1@example.com",
                            FullName = "User 5 (Role 1)",
                            IsActive = true,
                            LoginId = 5,
                            NationalID = "30101010000005",
                            PasswordHash = "$2a$11$dE4fG5h6I7j8K9l0M1n2O3p4Q5r6S7t8U9v0W1x2Y3z4A5b6c7D8e",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user6.role2@example.com",
                            FullName = "User 6 (Role 2)",
                            IsActive = true,
                            LoginId = 6,
                            NationalID = "30101010000006",
                            PasswordHash = "$2a$11$fG6hI7j8K9l0M1n2O3p4Q5r6S7t8U9v0W1x2Y3z4A5b6c7D8e9F0g",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user7.role2@example.com",
                            FullName = "User 7 (Role 2)",
                            IsActive = true,
                            LoginId = 7,
                            NationalID = "30101010000007",
                            PasswordHash = "$2a$11$hI8jK9l0M1n2O3p4Q5r6S7t8U9v0W1x2Y3z4A5b6c7D8e9F0g1H2i",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user8.role2@example.com",
                            FullName = "User 8 (Role 2)",
                            IsActive = true,
                            LoginId = 8,
                            NationalID = "30101010000008",
                            PasswordHash = "$2a$11$jK0lM1n2O3p4Q5r6S7t8U9v0W1x2Y3z4A5b6c7D8e9F0g1H2i3J4k",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user9.role2@example.com",
                            FullName = "User 9 (Role 2)",
                            IsActive = true,
                            LoginId = 9,
                            NationalID = "30101010000009",
                            PasswordHash = "$2a$11$lM2nO3p4Q5r6S7t8U9v0W1x2Y3z4A5b6c7D8e9F0g1H2i3J4k5L6m",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user10.role2@example.com",
                            FullName = "User 10 (Role 2)",
                            IsActive = true,
                            LoginId = 10,
                            NationalID = "30101010000010",
                            PasswordHash = "$2a$11$nO4pQ5r6S7t8U9v0W1x2Y3z4A5b6c7D8e9F0g1H2i3J4k5L6m7N8o",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user11.role3@example.com",
                            FullName = "User 11 (Role 3)",
                            IsActive = true,
                            LoginId = 11,
                            NationalID = "30101010000011",
                            PasswordHash = "$2a$11$pQ6rS7t8U9v0W1x2Y3z4A5b6c7D8e9F0g1H2i3J4k5L6m7N8o9P0q",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user12.role3@example.com",
                            FullName = "User 12 (Role 3)",
                            IsActive = true,
                            LoginId = 12,
                            NationalID = "30101010000012",
                            PasswordHash = "$2a$11$rS8tU9v0W1x2Y3z4A5b6c7D8e9F0g1H2i3J4k5L6m7N8o9P0q1R2s",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user13.role3@example.com",
                            FullName = "User 13 (Role 3)",
                            IsActive = true,
                            LoginId = 13,
                            NationalID = "30101010000013",
                            PasswordHash = "$2a$11$tU0vW1x2Y3z4A5b6c7D8e9F0g1H2i3J4k5L6m7N8o9P0q1R2s3T4u",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user14.role3@example.com",
                            FullName = "User 14 (Role 3)",
                            IsActive = true,
                            LoginId = 14,
                            NationalID = "30101010000014",
                            PasswordHash = "$2a$11$vW2xY3z4A5b6c7D8e9F0g1H2i3J4k5L6m7N8o9P0q1R2s3T4u5V6w",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user15.role3@example.com",
                            FullName = "User 15 (Role 3)",
                            IsActive = true,
                            LoginId = 15,
                            NationalID = "30101010000015",
                            PasswordHash = "$2a$11$xY4zA5b6c7D8e9F0g1H2i3J4k5L6m7N8o9P0q1R2s3T4u5V6w7X8y",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user16.role4@example.com",
                            FullName = "User 16 (Role 4)",
                            IsActive = true,
                            LoginId = 16,
                            NationalID = "30101010000016",
                            PasswordHash = "$2a$11$zA6bC7d8E9f0G1h2I3j4K5l6M7n8O9p0Q1r2S3t4U5v6W7x8Y9z0a",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user17.role4@example.com",
                            FullName = "User 17 (Role 4)",
                            IsActive = true,
                            LoginId = 17,
                            NationalID = "30101010000017",
                            PasswordHash = "$2a$11$bC8dE9f0G1h2I3j4K5l6M7n8O9p0Q1r2S3t4U5v6W7x8Y9z0a1B2c",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user18.role4@example.com",
                            FullName = "User 18 (Role 4)",
                            IsActive = true,
                            LoginId = 18,
                            NationalID = "30101010000018",
                            PasswordHash = "$2a$11$dE0fG1h2I3j4K5l6M7n8O9p0Q1r2S3t4U5v6W7x8Y9z0a1B2c3D4e",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user19.role4@example.com",
                            FullName = "User 19 (Role 4)",
                            IsActive = true,
                            LoginId = 19,
                            NationalID = "30101010000019",
                            PasswordHash = "$2a$11$fG2hI3j4K5l6M7n8O9p0Q1r2S3t4U5v6W7x8Y9z0a1B2c3D4e5F6g",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user20.role4@example.com",
                            FullName = "User 20 (Role 4)",
                            IsActive = true,
                            LoginId = 20,
                            NationalID = "30101010000020",
                            PasswordHash = "$2a$11$hI4jK5l6M7n8O9p0Q1r2S3t4U5v6W7x8Y9z0a1B2c3D4e5F6g7H8i",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user21.role5@example.com",
                            FullName = "User 21 (Role 5)",
                            IsActive = true,
                            LoginId = 21,
                            NationalID = "30101010000021",
                            PasswordHash = "$2a$11$jK6lM7n8O9p0Q1r2S3t4U5v6W7x8Y9z0a1B2c3D4e5F6g7H8i9J0k",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user22.role5@example.com",
                            FullName = "User 22 (Role 5)",
                            IsActive = true,
                            LoginId = 22,
                            NationalID = "30101010000022",
                            PasswordHash = "$2a$11$lM8nO9p0Q1r2S3t4U5v6W7x8Y9z0a1B2c3D4e5F6g7H8i9J0k1L2m",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user23.role5@example.com",
                            FullName = "User 23 (Role 5)",
                            IsActive = true,
                            LoginId = 23,
                            NationalID = "30101010000023",
                            PasswordHash = "$2a$11$nO0pQ1r2S3t4U5v6W7x8Y9z0a1B2c3D4e5F6g7H8i9J0k1L2m3N4o",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user24.role5@example.com",
                            FullName = "User 24 (Role 5)",
                            IsActive = true,
                            LoginId = 24,
                            NationalID = "30101010000024",
                            PasswordHash = "$2a$11$pQ2rS3t4U5v6W7x8Y9z0a1B2c3D4e5F6g7H8i9J0k1L2m3N4o5P6q",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user25.role5@example.com",
                            FullName = "User 25 (Role 5)",
                            IsActive = true,
                            LoginId = 25,
                            NationalID = "30101010000025",
                            PasswordHash = "$2a$11$rS4tU5v6W7x8Y9z0a1B2c3D4e5F6g7H8i9J0k1L2m3N4o5P6q7R8s",
                            RoleId = 5
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user26.role6@example.com",
                            FullName = "User 26 (Role 6)",
                            IsActive = true,
                            LoginId = 26,
                            NationalID = "30101010000026",
                            PasswordHash = "$2a$11$tU6vW7x8Y9z0a1B2c3D4e5F6g7H8i9J0k1L2m3N4o5P6q7R8s9T0u",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user27.role6@example.com",
                            FullName = "User 27 (Role 6)",
                            IsActive = true,
                            LoginId = 27,
                            NationalID = "30101010000027",
                            PasswordHash = "$2a$11$vW8xY9z0a1B2c3D4e5F6g7H8i9J0k1L2m3N4o5P6q7R8s9T0u1V2w",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user28.role6@example.com",
                            FullName = "User 28 (Role 6)",
                            IsActive = true,
                            LoginId = 28,
                            NationalID = "30101010000028",
                            PasswordHash = "$2a$11$xY0zA1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0U1v2W3x4y",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user29.role6@example.com",
                            FullName = "User 29 (Role 6)",
                            IsActive = true,
                            LoginId = 29,
                            NationalID = "30101010000029",
                            PasswordHash = "$2a$11$zA2bC3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0U1v2W3x4y5Z6a",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user30.role6@example.com",
                            FullName = "User 30 (Role 6)",
                            IsActive = true,
                            LoginId = 30,
                            NationalID = "30101010000030",
                            PasswordHash = "$2a$11$bC4dE5f6G7h8I9j0K1l2M3n4O5p6Q7r8S9t0U1v2W3x4y5Z6a7B8c",
                            RoleId = 6
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user31.role7@example.com",
                            FullName = "User 31 (Role 7)",
                            IsActive = true,
                            LoginId = 31,
                            NationalID = "30101010000031",
                            PasswordHash = "$2a$11$dE6fG7h8I9j0K1l2M3n4O5p6Q7r8S9t0U1v2W3x4y5Z6a7B8c9D0e",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user32.role7@example.com",
                            FullName = "User 32 (Role 7)",
                            IsActive = true,
                            LoginId = 32,
                            NationalID = "30101010000032",
                            PasswordHash = "$2a$11$fG8hI9j0K1l2M3n4O5p6Q7r8S9t0U1v2W3x4y5Z6a7B8c9D0e1F2g",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user33.role7@example.com",
                            FullName = "User 33 (Role 7)",
                            IsActive = true,
                            LoginId = 33,
                            NationalID = "30101010000033",
                            PasswordHash = "$2a$11$hI0jK1l2M3n4O5p6Q7r8S9t0U1v2W3x4y5Z6a7B8c9D0e1F2g3H4i",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user34.role7@example.com",
                            FullName = "User 34 (Role 7)",
                            IsActive = true,
                            LoginId = 34,
                            NationalID = "30101010000034",
                            PasswordHash = "$2a$11$jK2lM3n4O5p6Q7r8S9t0U1v2W3x4y5Z6a7B8c9D0e1F2g3H4i5J6k",
                            RoleId = 7
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user35.role7@example.com",
                            FullName = "User 35 (Role 7)",
                            IsActive = true,
                            LoginId = 35,
                            NationalID = "30101010000035",
                            PasswordHash = "$2a$11$lM4nO5p6Q7r8S9t0U1v2W3x4y5Z6a7B8c9D0e1F2g3H4i5J6k7L8m",
                            RoleId = 7
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClassRooms");
                });

            modelBuilder.Entity("RegisterAPII.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("RegisterAPII.Models.LoginAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Email = "user1.role1@example.com",
                            NationalID = "30101010000001",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Email = "user2.role1@example.com",
                            NationalID = "30101010000002",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            Email = "user3.role1@example.com",
                            NationalID = "30101010000003",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            Email = "user4.role1@example.com",
                            NationalID = "30101010000004",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            Email = "user5.role1@example.com",
                            NationalID = "30101010000005",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 6,
                            Email = "user6.role2@example.com",
                            NationalID = "30101010000006",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 7,
                            Email = "user7.role2@example.com",
                            NationalID = "30101010000007",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 8,
                            Email = "user8.role2@example.com",
                            NationalID = "30101010000008",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 9,
                            Email = "user9.role2@example.com",
                            NationalID = "30101010000009",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 10,
                            Email = "user10.role2@example.com",
                            NationalID = "30101010000010",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 11,
                            Email = "user11.role3@example.com",
                            NationalID = "30101010000011",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 12,
                            Email = "user12.role3@example.com",
                            NationalID = "30101010000012",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 13,
                            Email = "user13.role3@example.com",
                            NationalID = "30101010000013",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 14,
                            Email = "user14.role3@example.com",
                            NationalID = "30101010000014",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 15,
                            Email = "user15.role3@example.com",
                            NationalID = "30101010000015",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 16,
                            Email = "user16.role4@example.com",
                            NationalID = "30101010000016",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 17,
                            Email = "user17.role4@example.com",
                            NationalID = "30101010000017",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 18,
                            Email = "user18.role4@example.com",
                            NationalID = "30101010000018",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 19,
                            Email = "user19.role4@example.com",
                            NationalID = "30101010000019",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 20,
                            Email = "user20.role4@example.com",
                            NationalID = "30101010000020",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 21,
                            Email = "user21.role5@example.com",
                            NationalID = "30101010000021",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 22,
                            Email = "user22.role5@example.com",
                            NationalID = "30101010000022",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 23,
                            Email = "user23.role5@example.com",
                            NationalID = "30101010000023",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 24,
                            Email = "user24.role5@example.com",
                            NationalID = "30101010000024",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 25,
                            Email = "user25.role5@example.com",
                            NationalID = "30101010000025",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 26,
                            AccountId = 26,
                            Email = "user26.role6@example.com",
                            NationalID = "30101010000026",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 27,
                            AccountId = 27,
                            Email = "user27.role6@example.com",
                            NationalID = "30101010000027",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 28,
                            AccountId = 28,
                            Email = "user28.role6@example.com",
                            NationalID = "30101010000028",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 29,
                            AccountId = 29,
                            Email = "user29.role6@example.com",
                            NationalID = "30101010000029",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 30,
                            AccountId = 30,
                            Email = "user30.role6@example.com",
                            NationalID = "30101010000030",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 31,
                            AccountId = 31,
                            Email = "user31.role7@example.com",
                            NationalID = "30101010000031",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 32,
                            AccountId = 32,
                            Email = "user32.role7@example.com",
                            NationalID = "30101010000032",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 33,
                            AccountId = 33,
                            Email = "user33.role7@example.com",
                            NationalID = "30101010000033",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 34,
                            AccountId = 34,
                            Email = "user34.role7@example.com",
                            NationalID = "30101010000034",
                            Password = "StrongPassword123"
                        },
                        new
                        {
                            Id = 35,
                            AccountId = 35,
                            Email = "user35.role7@example.com",
                            NationalID = "30101010000035",
                            Password = "StrongPassword123"
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Student"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Specialist"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "It"
                        },
                        new
                        {
                            RoleId = 6,
                            Name = "Teacher"
                        },
                        new
                        {
                            RoleId = 7,
                            Name = "Engineer"
                        },
                        new
                        {
                            RoleId = 8,
                            Name = "Parent"
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("sessionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RegisterAPII.Models.SubordinateTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassRoomId")
                        .HasColumnType("int");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SubordinateAccountId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorAccountId")
                        .HasColumnType("int");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("subordinateTickets");
                });

            modelBuilder.Entity("RegisterAPII.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessEntity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            BusinessEntity = "Behaviour",
                            Name = "Late",
                            OrderNo = 10
                        },
                        new
                        {
                            Id = 7,
                            BusinessEntity = "Behaviour",
                            Name = "Eating",
                            OrderNo = 30
                        },
                        new
                        {
                            Id = 10,
                            BusinessEntity = "Behaviour",
                            Name = "SideTalks",
                            OrderNo = 20
                        },
                        new
                        {
                            Id = 12,
                            BusinessEntity = "Absence",
                            Name = "Absence",
                            OrderNo = 10
                        });
                });

            modelBuilder.Entity("RegisterAPII.Models.Accounts", b =>
                {
                    b.HasOne("RegisterAPII.Models.LoginAccount", "LoginAccount")
                        .WithOne("Accounts")
                        .HasForeignKey("RegisterAPII.Models.Accounts", "LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegisterAPII.Models.Role", "Role")
                        .WithMany("Account")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoginAccount");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RegisterAPII.Models.LoginAccount", b =>
                {
                    b.Navigation("Accounts")
                        .IsRequired();
                });

            modelBuilder.Entity("RegisterAPII.Models.Role", b =>
                {
                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
